# Generated by Django 5.1.7 on 2025-04-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
